apiVersion: v1
kind: Service
metadata:
  name: profile-ui
  namespace: profile-ui
spec:
  selector:
    app: profile-ui
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 80
  type: NodePort
